const moongoose=require('mongoose');
//define a comment schema for the database
const productSchema = new mongoose.Schema({
    name: {
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    description:{
        type:String,
        required:false
    }, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
    imageUrl:{
        type:String,
        required:false
    }
  });
  
  // compile model from schema
  module.exports = mongoose.model("product", productSchema);